module.exports = {
    APP_CREATE_PLAN: "APP_CREATE_PLAN",
    APP_DEL_PLAN: "APP_DEL_PLAN",
    APP_UPDATE_PLAN_TEXT: "APP_UPDATE_PLAN_TEXT",
    APP_SELECT_PLAN: "APP_SELECT_PLAN",
    APP_CREATE_NODE: "APP_CREATE_NODE",
    APP_DEL_NODE: "APP_DEL_NODE",
    APP_UPDATE_NODE_CONTENT: "APP_UPDATE_NODE_CONTENT",
}