const AppConstants = {
    CREATE_PLAN: "CREATE_PLAN", // done
    REMOVE_PLAN: "REMOVE_PLAN",
    SELECT_PLAN: "SELECT_PLAN",
    // SWAP_PLAN: "SWAP_PLAN",
    EDIT_PLAN: "EDIT_PLAN",
    TOGGLE_PLAN: "TOGGLE_PLAN",
    SHARE_PLAN: "SHARE_PLAN",
    CREATE_NODE: "CREATE_NODE", // done
    REMOVE_NODE: "REMOVE_NOD",
    SWAP_NODE: "SWAP_NODE",
    EDIT_NODE: "EDIT_NOD",
    TOGGLE_NODE: "TOGGLE_NODE"
};

export default AppConstants;